name: lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  black:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2

      - name: Install black
        run: pip install black==24.2.0

      - name: Run black
        run: black --exclude 'stubs\/' --check --diff .

  flake8:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2

      - name: Install flake8
        run: pip install flake8

      - name: Run flake8
        run: flake8

  ESLint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install packages and run ESLint
        run: |
          cd sapp/ui/frontend
          npm install
          npm install -g eslint
          npm run lint
